//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Мод.Разр.Пецевич_ПР22_102_практ5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Checks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Checks()
        {
            this.Tax_reports = new HashSet<Tax_reports>();
        }
    
        public int Operation_ID { get; set; }
        public int Material_ID { get; set; }
        public Nullable<int> Supplier_ID { get; set; }
        public decimal Quantity { get; set; }
        public System.DateTime Operation_date { get; set; }
        public int Type_ID { get; set; }
    
        public virtual Materials Materials { get; set; }
        public virtual Suppliers Suppliers { get; set; }
        public virtual Operation_type Operation_type { get; set; }
        public virtual Operation_type Operation_type1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tax_reports> Tax_reports { get; set; }
    }
}
