//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Мод.Разр.Пецевич_ПР22_102_практ5.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ХлебопекарняEntities1 : DbContext
    {
        public ХлебопекарняEntities1()
            : base("name=ХлебопекарняEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Authorization> Authorization { get; set; }
        public virtual DbSet<Checks> Checks { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Materials> Materials { get; set; }
        public virtual DbSet<Operation_type> Operation_type { get; set; }
        public virtual DbSet<Order_details> Order_details { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Positions> Positions { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Sales_points> Sales_points { get; set; }
        public virtual DbSet<Suppliers> Suppliers { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tax_reports> Tax_reports { get; set; }
        public virtual DbSet<Work_schedule> Work_schedule { get; set; }
    }
}
