//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Мод.Разр.Пецевич_ПР22_102_практ5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tax_reports
    {
        public int Report_ID { get; set; }
        public System.DateTime Report_date { get; set; }
        public decimal Total_revenue { get; set; }
        public decimal Total_expenses { get; set; }
        public int Employee_ID { get; set; }
        public int Operation_ID { get; set; }
        public int Order_ID { get; set; }
    
        public virtual Checks Checks { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
